# Generated by Django 5.2.17 on 2026-08-19 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("landlord", "Landlord"), ("searcher", "Searcher")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.CharField(blank=True, max_length=150)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="lucide-react icon name, e.g. 'Rocket', 'Crown'.",
                        max_length=40,
                    ),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "max_active_listings",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Landlord plans only. Blank = unlimited.",
                        null=True,
                    ),
                ),
                (
                    "max_saved_properties",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Searcher plans only. Blank = unlimited.",
                        null=True,
                    ),
                ),
                (
                    "max_landlord_contacts_per_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Searcher plans only. Blank = unlimited.",
                        null=True,
                    ),
                ),
                ("has_ai_matching", models.BooleanField(default=False)),
                ("has_priority_support", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["role", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=150)),
                ("included", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("payment_provider", models.CharField(default="stub", max_length=30)),
                ("external_reference", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="subscriptio_user_id_2a19e8_idx"
                    )
                ],
            },
        ),
    ]
